version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: email_sorter_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: email_sorter
    ports:
      - "54321:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: email_sorter_redis
    ports:
      - "63791:6379"

volumes:
  postgres_data:
